[workspace]
members = ["xcb-code-generator", "xcb-rust-connection", "xcb-rust-protocol", "xcb-xsd", "xcb-xsd-parser"]

[workspace.dependencies]
smallmap = { version = "1.4.1", default-features = false }
rusl = { version = "0.1.0" }
tiny-std = { version = "0.1.0" }
unix-print = "0.1.0"
