[workspace]
members = ["xcb-code-generator", "xcb-rust-connection", "xcb-rust-protocol", "xcb-xsd", "xcb-xsd-parser"]

[workspace.dependencies]
rusl = { path = "../tiny-std/rusl" }
smallmap = { git = "https://github.com/MarcusGrass/smallmap.git", rev = "a0e7399d09a22753ef9c80aa1f1a34009b364357", default-features = false }
tiny-std = { path = "../tiny-std/tiny-std" }
unix-print = "0.1.0"
